apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: sqiv13fcs-python 
  janus-idp.io/tekton: sqiv13fcs-python
  backstage.io/kubernetes-id: sqiv13fcs-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: sqiv13fcs-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml