apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sqiv13fcs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sqiv13fcs-python 
  name: sqiv13fcs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sqiv13fcs-python 
